name: Generate LeetCode Contribution Grid

on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run automatically on a schedule (e.g., every 12 hours)
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate LeetCode-style contribution grid
        # <<< THIS LINE IS CORRECTED
        uses: grubersjoe/github-contributions-grid-svg@main
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}
          
          # The output file path
          svg_file_path: "contributions.svg"
          
          # Customization URL to match LeetCode theme
          custom_url: "https://github-contributions.vercel.app/api/v1/${{ github.repository_owner }}?color_scheme=dark&bg_color=0D1117&border_color=0D1117&color_4=59D561&color_3=39d353&color_2=26a641&color_1=006d32"
          
          # The comment markers from your README
          comment_start: "<!--START_SECTION:contributions-grid-->"
          comment_end: "<!--END_SECTION:contributions-grid-->"
          
          # Commit details
          commit_message: "chore: Update LeetCode contribution grid"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
